# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d16d58a0ef4520a9dcc6f163e7566d81afe546aed512e9f8c480a496b63eee3aa1249b2d40b775ee08ab145cc97ddc1b8d35d88506386fc399e6568d243afd8a

test:
  secret_key_base: b8815404716bf962c949ad1918857649ad34de9edcde249132139b8f3a1d38e352fdf803c350d6b6ac22c606d29a71ee3a07ac3518628425cc55e333f67aecb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
